/**
 * \file
 * \brief Generated grid configuration constants.
 * \note This file is automatically generated. Do not edit manually.
 */

#ifndef BELUGA_GENERATED_GRID_CONFIG_HPP
#define BELUGA_GENERATED_GRID_CONFIG_HPP

#include <cstddef>

/// Number of rows in the occupancy grid.
static constexpr std::size_t kGridRows = 140;

/// Number of columns in the occupancy grid.
static constexpr std::size_t kGridCols = 140;

/// Grid resolution in meters per cell.
static constexpr double kGridResolution = 0.05;

/// X-coordinate of the grid origin in the map frame.
static constexpr double kOriginX = -3.5;

/// Y-coordinate of the grid origin in the map frame.
static constexpr double kOriginY = -5.25;

#endif  // BELUGA_GENERATED_GRID_CONFIG_HPP
