/**
 * \file
 * \brief Generated grid configuration constants.
 * \note This file is automatically generated. Do not edit manually.
 */

#ifndef BELUGA_GENERATED_GRID_CONFIG_HPP
#define BELUGA_GENERATED_GRID_CONFIG_HPP

#include <cstddef>
/// Occupancy state values following ROS 2 nav_msgs convention.

static constexpr std::int8_t kOccupiedValue = 100;
static constexpr std::int8_t kFreeValue = 0;
static constexpr std::int8_t kUnknownValue = -1;

/// Physical robot parameters.
static constexpr double kRobotRadius = 0.7;

/// Number of rows in the occupancy grid.
static constexpr std::size_t kGridRows = 300;

/// Number of columns in the occupancy grid.
static constexpr std::size_t kGridCols = 300;

/// Grid resolution in meters per cell.
static constexpr double kGridResolution = 0.1;

/// X-coordinate of the grid origin in the map frame.
static constexpr double kOriginX = -22.5;

/// Y-coordinate of the grid origin in the map frame.
static constexpr double kOriginY = -7.5;

#endif  // BELUGA_GENERATED_GRID_CONFIG_HPP
