/**
 * \file
 * \brief Generated grid configuration constants.
 * \note This file is automatically generated. Do not edit manually.
 */

#ifndef BELUGA_GENERATED_GRID_CONFIG_HPP
#define BELUGA_GENERATED_GRID_CONFIG_HPP

#include <cstddef>
/// Occupancy state values following ROS 2 nav_msgs convention.

static constexpr std::int8_t kOccupiedValue = 100;
static constexpr std::int8_t kFreeValue = 0;
static constexpr std::int8_t kUnknownValue = -1;

/// Physical robot parameters.
static constexpr double kRobotRadius = 0.01;

/// Number of rows in the occupancy grid.
static constexpr std::size_t kGridRows = 111;

/// Number of columns in the occupancy grid.
static constexpr std::size_t kGridCols = 111;

/// Grid resolution in meters per cell.
static constexpr double kGridResolution = 0.05;

/// X-coordinate of the grid origin in the map frame.
static constexpr double kOriginX = -2.7750000000000004;

/// Y-coordinate of the grid origin in the map frame.
static constexpr double kOriginY = -4.856250000000001;

#endif  // BELUGA_GENERATED_GRID_CONFIG_HPP
