// Copyright 2022-2023 Ekumen, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef BELUGA_MOTION_DIFFERENTIAL_DRIVE_DISTRIBUTION_HPP
#define BELUGA_MOTION_DIFFERENTIAL_DRIVE_DISTRIBUTION_HPP
#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <random>
#include <stdexcept>

namespace beluga {
/// Parameters to construct a DifferentialDriveModel instance.
/**
 * See Probabilistic Robotics \cite thrun2005probabilistic Chapter 5.4.2, particularly table 5.6.
 */
struct DifferentialDriveModelParam {
  /// Rotational noise from rotation
  /**
   * How much rotational noise is generated by the relative rotation between the last two odometry updates.
   * Also known as `alpha1`.
   */
  double rotation_noise_from_rotation;
  /// Rotational noise from translation
  /**
   * How much rotational noise is generated by the relative translation between the last two odometry updates.
   * Also known as `alpha2`.
   */
  double rotation_noise_from_translation;
  /// Translational noise from translation
  /**
   * How much translational noise is generated by the relative translation between the last two odometry updates.
   * Also known as `alpha3`.
   */
  double translation_noise_from_translation;
  /// Translational noise from rotation
  /**
   * How much translational noise is generated by the relative rotation between the last two odometry updates.
   * Also known as `alpha4`.
   */
  double translation_noise_from_rotation;

  /// Distance threshold to detect in-place rotation.
  double distance_threshold = 0.01;
};


namespace motion_detail {
constexpr double pi = 3.14159265358979323846;
inline double wrap(double a) { return std::remainder(a, 2*pi); }
inline double log_add(double a, double b) {
  if (a == -std::numeric_limits<double>::infinity()) return b;
  if (b == -std::numeric_limits<double>::infinity()) return a;
  return std::max(a,b) + std::log1p(std::exp(-std::abs(a-b)));
}
inline double normal_log_density(double x, double mean, double sigma) {
  const double z=(x-mean)/sigma;
  return -.5*z*z-std::log(sigma)-.5*std::log(2*pi);
}
// Wrapped normal density on S1. Image sum for narrow noise, Fourier series
// for broad noise; tails below floating-point relevance, no nearest-angle-only
// approximation at +/-pi. All densities use radians and dx dy dtheta measure.
inline double wrapped_normal_log_density(double angle, double mean, double sigma) {
  const double d=wrap(angle-mean);
  if (sigma < 1.) {
    double result=-std::numeric_limits<double>::infinity();
    for (int k=-2;k<=2;++k)
      result=log_add(result,normal_log_density(d+2*pi*k,0,sigma));
    return result;
  }
  double sum=1.;
  for (int k=1;k<=12;++k) {
    const double term=2*std::exp(-.5*k*k*sigma*sigma);
    sum+=term*std::cos(k*d);
    if (term<1e-16) break;
  }
  return std::log(sum)-std::log(2*pi);
}
}  // namespace motion_detail

struct DifferentialDriveDistribution2d {
  double first_mean=0, distance_mean=0, second_mean=0;
  double first_sigma=0, distance_sigma=0, second_sigma=0;
  // A shifted continuous proposal cannot importance-correct a singular prior.
  // Very small sigmas also use bootstrap sampling to avoid numerical singularity.
  [[nodiscard]] bool has_density() const {
    return first_sigma>1e-9 && distance_sigma>1e-9 && second_sigma>1e-9 &&
      std::isfinite(first_sigma) && std::isfinite(distance_sigma) && std::isfinite(second_sigma);
  }
  template<class Generator>
  std::array<double,3> sample(Generator& gen) const {
    const auto draw=[&](double mean,double sigma) {
      return sigma==0 ? mean : std::normal_distribution<double>{mean,sigma}(gen);
    };
    const double a=draw(first_mean,first_sigma), d=draw(distance_mean,distance_sigma);
    const double b=draw(second_mean,second_sigma);
    return {d*std::cos(a),d*std::sin(a),motion_detail::wrap(a+b)};
  }
  // The sampler permits NEGATIVE distance. Sum both polar preimages and
  // divide by |distance| (polar Jacobian). Ignoring either biases p/q.
  [[nodiscard]] double log_density(double x,double y,double yaw) const {
    if (!has_density()) throw std::invalid_argument("Singular odometry density: use bootstrap proposal");
    const double radius=std::hypot(x,y), bearing=std::atan2(y,x);
    if (!(radius>0) || !std::isfinite(radius) || !std::isfinite(yaw))
      return -std::numeric_limits<double>::infinity(); // measure-zero coordinate singularity
    const auto branch=[&](double d,double a) {
      return motion_detail::normal_log_density(d,distance_mean,distance_sigma) +
        motion_detail::wrapped_normal_log_density(a,first_mean,first_sigma) +
        motion_detail::wrapped_normal_log_density(yaw-a,second_mean,second_sigma);
    };
    return motion_detail::log_add(branch(radius,bearing),branch(-radius,bearing+motion_detail::pi)) -
      std::log(radius);
  }
};

inline DifferentialDriveDistribution2d make_differential_drive_distribution(
    double distance,double first,double second,double turn,const DifferentialDriveModelParam& p) {
  const auto variance=[](double angle) {
    const double r=std::min(std::abs(motion_detail::wrap(angle)),
                            std::abs(motion_detail::wrap(angle+motion_detail::pi)));
    return r*r;
  };
  const double r1=distance>p.distance_threshold ? variance(first) : 0.;
  const double r2=distance>p.distance_threshold ? variance(second) : variance(turn);
  const double d2=distance*distance;
  return {first,distance,second,
    std::sqrt(p.rotation_noise_from_rotation*r1+p.rotation_noise_from_translation*d2),
    std::sqrt(p.translation_noise_from_translation*d2+p.translation_noise_from_rotation*(r1+r2)),
    std::sqrt(p.rotation_noise_from_rotation*r2+p.rotation_noise_from_translation*d2)};
}
}  // namespace beluga
#endif
