#!/usr/bin/env python3
"""
FastSLAM Grid Configuration Generator.
This script defines the physical constraints of the occupancy grid
and generates the corresponding C++ header file.
"""

import os

# MIT Rosbag: 1, Intel Dataset: 2, Beluga Rosbag: 3
ENV = 4

if ENV == 1:
    GRID_ROWS = 300
    GRID_RESOLUTION = 0.1 
    GRID_COLS = GRID_ROWS
    ORIGIN_X = - float(GRID_COLS) * GRID_RESOLUTION * 0.75
    ORIGIN_Y = - float(GRID_COLS) * GRID_RESOLUTION * 0.25
elif ENV == 2:
    GRID_ROWS = 350
    GRID_RESOLUTION = 0.1 
    GRID_COLS = GRID_ROWS
    ORIGIN_X = - float(GRID_COLS) * GRID_RESOLUTION * 0.375
    ORIGIN_Y = - float(GRID_COLS) * GRID_RESOLUTION * 0.75
elif ENV == 3:
    GRID_ROWS = 700
    GRID_RESOLUTION = 0.01 
    GRID_COLS = GRID_ROWS
    ORIGIN_X = - float(GRID_COLS) * GRID_RESOLUTION * 0.5
    ORIGIN_Y = - float(GRID_COLS) * GRID_RESOLUTION * 0.75
else: 
    GRID_ROWS = 140
    GRID_RESOLUTION = 0.05
    GRID_COLS = GRID_ROWS
    ORIGIN_X = - float(GRID_COLS) * GRID_RESOLUTION * 0.5
    ORIGIN_Y = - float(GRID_COLS) * GRID_RESOLUTION * 0.75

def generate_header(output_path):
    content = f"""/**
 * \\file
 * \\brief Generated grid configuration constants.
 * \\note This file is automatically generated. Do not edit manually.
 */

#ifndef BELUGA_GENERATED_GRID_CONFIG_HPP
#define BELUGA_GENERATED_GRID_CONFIG_HPP

#include <cstddef>

/// Number of rows in the occupancy grid.
static constexpr std::size_t kGridRows = {GRID_ROWS};

/// Number of columns in the occupancy grid.
static constexpr std::size_t kGridCols = {GRID_COLS};

/// Grid resolution in meters per cell.
static constexpr double kGridResolution = {GRID_RESOLUTION};

/// X-coordinate of the grid origin in the map frame.
static constexpr double kOriginX = {ORIGIN_X};

/// Y-coordinate of the grid origin in the map frame.
static constexpr double kOriginY = {ORIGIN_Y};

#endif  // BELUGA_GENERATED_GRID_CONFIG_HPP
"""
    with open(output_path, 'w') as f:
        f.write(content)
    print(f"Header generated at: {output_path}")

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    output_folder = os.path.join(script_dir, "..", "include", "fastslam_core")
    
    os.makedirs(output_folder, exist_ok=True)
    
    output_path = os.path.join(output_folder, "grid_config.hpp")
    generate_header(output_path)